# function.read_excel_allsheets.dev.r


#@ https://stackoverflow.com/questions/12945687/read-all-worksheets-in-an-excel-workbook-into-an-r-list-with-data-frames ====
library(tidyverse)
library(readxl)
?readxl::excel_sheets
?readxl::read_excel

function.read_excel_allsheets <- function(filename, col_names = TRUE, col_types = NULL, na = "", trim_ws = TRUE, skip = 0, n_max = Inf, guess_max = min(1000, n_max), tibble = TRUE) {
    sheetnames <- readxl::excel_sheets(filename)
    out = map(sheetnames, function(X, ...) {
        readxl::read_excel(filename, sheet = X, col_names = col_names, col_types = col_types, na = na, trim_ws = trim_ws, skip = skip, n_max = n_max, guess_max = guess_max)
    }) %>% set_names(sheetnames)
    if(!tibble) out = map(out, as.data.frame)
    out
}
MarketScan_Introduction2README = function.read_excel_allsheets("MarketScan_Introduction2README.xlsx", col_names = F)
MarketScan_Introduction2README |> str()
# > MarketScan_Introduction2README |> str()
# List of 16
#  $ LS.WOMEN_PREGCOHORT_S_R4     :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	47 obs. of  2 variables:
#   ..$ X__1: chr [1:47] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:47] "A look-up dataset for all inpatient claims for women in the pregnancy cohort." "47480226" "1977863" "Date of admission" ...
#  $ LS.INFANT_PREGCOHORT_S_R4    :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	47 obs. of  2 variables:
#   ..$ X__1: chr [1:47] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:47] "A look-up dataset for all inpatient claims for women in the pregnancy cohort." "47480226" "1977863" "Date of admission" ...
#  $ LS.WOMEN_PREGCOHORT_O_R4     :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	39 obs. of  2 variables:
#   ..$ X__1: chr [1:39] "Summary" "# of Observations" "# of Unique ENROLID" "AGE" ...
#   ..$ X__2: chr [1:39] "A look-up dataset for all outpatient claims for women in the pregnancy cohort." "236830420" "2372042" "Age of patient" ...
#  $ LS.INFANT_PREGCOHORT_O_R4    :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	39 obs. of  2 variables:
#   ..$ X__1: chr [1:39] "Summary" "# of Observations" "# of Unique ENROLID" "AGE" ...
#   ..$ X__2: chr [1:39] "A look-up dataset for all outpatient claims for infants in the pregnancy cohort." "82690025" "1498751" "Age of patient" ...
#  $ LS.WOMEN_PREGCOHORT_T_R4     :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	12 obs. of  2 variables:
#   ..$ X__1: chr [1:12] "Summary" "# of Observations" "# of Unique ENROLID" "AGE" ...
#   ..$ X__2: chr [1:12] "A look-up dataset for all enrollment claims for women in the pregnancy cohort." "74512065" "2379122" "Age of Patient" ...
#  $ LS.INFANT_PREGCOHORT_T_R4    :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	12 obs. of  2 variables:
#   ..$ X__1: chr [1:12] "Summary" "# of Observations" "# of Unique ENROLID" "AGE" ...
#   ..$ X__2: chr [1:12] "A look-up dataset for all enrollment claims for infant in the pregnancy cohort." "26707431" "1503767" "Age of Patient" ...
#  $ LS.WOMEN_PREGCOHORT_D_R4     :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	36 obs. of  2 variables:
#   ..$ X__1: chr [1:36] "Summary" "# of Observations" "# of Unique ENROLID" "AGE" ...
#   ..$ X__2: chr [1:36] "A look-up dataset for all prescription claims for women in the pregnancy cohort." "45994754" "1835396" "Age of Patient" ...
#  $ LS.INFANT_PREGCOHORT_D_R4    :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	36 obs. of  2 variables:
#   ..$ X__1: chr [1:36] "Summary" "# of Observations" "# of Unique ENROLID" "AGE" ...
#   ..$ X__2: chr [1:36] "A look-up dataset for all prescription claims for infants in the pregnancy cohort." "8717967" "617969" "Age of Patient" ...
#  $ LS.WOMEN_PREGCOHORT_I_R4     :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	42 obs. of  2 variables:
#   ..$ X__1: chr [1:42] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:42] "A look-up dataset for all Inpatient Admission claims for infants in the pregnancy cohort." "2365456" "1976159" "Date of admission" ...
#  $ LS.INFANT_PREGCOHORT_I_R4    :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	42 obs. of  2 variables:
#   ..$ X__1: chr [1:42] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:42] "A look-up dataset for all Inpatient Admission claims for infants in the pregnancy cohort." "1184202" "1073318" "Date of admission" ...
#  $ LS.WOMEN_PREGCOHORT_S_R4_MOD :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	31 obs. of  2 variables:
#   ..$ X__1: chr [1:31] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:31] "A look-up dataset for all inpatient claims for women in the pregnancy cohort. Formatted “long” so each row is a"| __truncated__ "35425132" "1977863" "Date of admission" ...
#  $ LS.INFANT_PREGCOHORT_S_R4_MOD:Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	31 obs. of  2 variables:
#   ..$ X__1: chr [1:31] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:31] "A look-up dataset for all inpatient claims for infants in the pregnancy cohort. Formatted “long” so each row is"| __truncated__ "25068718" "1074830" "Date of admission" ...
#  $ LS.WOMEN_PREGCOHORT_O_R4_MOD :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	28 obs. of  2 variables:
#   ..$ X__1: chr [1:28] "Summary" "# of Observations" "# of Unique ENROLID" "DXVER" ...
#   ..$ X__2: chr [1:28] "A look-up dataset for all outpatient claims for women in the pregnancy cohort. Formatted “long” so each row is "| __truncated__ "334467797" "2372042" "Indicator for whether we’re using ICD-9-CM or ICD-10-CM" ...
#  $ LS.INFANT_PREGCOHORT_O_R4_MOD:Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	28 obs. of  2 variables:
#   ..$ X__1: chr [1:28] "Summary" "# of Observations" "# of Unique ENROLID" "DXVER" ...
#   ..$ X__2: chr [1:28] "A look-up dataset for all outpatient claims for infant in the pregnancy cohort. Formatted “long” so each row is"| __truncated__ "119757129" "1498734" "Indicator for whether we’re using ICD-9-CM or ICD-10-CM" ...
#  $ LS.MSCAN_PREGCOHORT_R4       :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	52 obs. of  2 variables:
#   ..$ X__1: chr [1:52] "Summary" "# of Observations" "# of Unique ENROLID" "Deliv_caseid1-8" ...
#   ..$ X__2: chr [1:52] "Summary dataset of all the pregnancies in the cohort" "2785245" "2379761" "The CASEID for the hospital admission of delivery" ...
#  $ LS.MSCAN_DELIVRANGE_OS_R4    :Classes ‘tbl_df’, ‘tbl’ and 'data.frame':	35 obs. of  2 variables:
#   ..$ X__1: chr [1:35] "Summary" "# of Observations" "# of Unique ENROLID" "ADMDATE" ...
#   ..$ X__2: chr [1:35] "Look-up dataset for the claims incurred between delivrange_start and delivrange_end and/or the full hospital ad"| __truncated__ "41868404" "2379761" "Date of admission" ...





#@ end ----
