
import os
import requests

# Create a directory to save the images
output_dir = 'rstudio_theme_images'
os.makedirs(output_dir, exist_ok=True)

# List of theme names and corresponding image URLs
themes = [
    {'theme_name': '49th Parallel', 'url': 'https://raw.githubusercontent.com/wvictor14/rstudio_themes/master/images/preview_49th_parallel.png'},
    {'theme_name': 'a11y-dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/a11y_dark.png'},
    {'theme_name': 'AABH FUNS SPECIFIED', 'url': 'https://raw.githubusercontent.com/noah-silver/R-Studio-Custom-Themes/master/aabh_funs_specified/aabh_funs_specified_example.PNG'},
    {'theme_name': 'Ace', 'url': 'https://raw.githubusercontent.com/AnthonyEbert/rstudio-ace/main/ace.png'},
    {'theme_name': 'Adam One Dark', 'url': 'https://raw.githubusercontent.com/adamoshen/adam-rstheme/main/img/dark-preview.png'},
    {'theme_name': 'Adam One Light', 'url': 'https://raw.githubusercontent.com/adamoshen/adam-rstheme/main/img/light-preview.png'},
    {'theme_name': 'Ariake Dark', 'url': 'https://raw.githubusercontent.com/lusignan/rstudio-ariake-dark/main/img/screenshot.png'},
    {'theme_name': 'Asher Theme', 'url': 'https://raw.githubusercontent.com/michaelasher/CustomRStudioTheme/master/images/RStudioAsherAppearance.png'},
    {'theme_name': 'Atarax 4', 'url': 'https://raw.githubusercontent.com/HeitorGabriel/R_theme/main/workspace.png'},
    {'theme_name': 'ayu-dark', 'url': 'https://raw.githubusercontent.com/graiffgarcia/ayu-ish-rstudio/master/assets/ayu-dark.png'},
    {'theme_name': 'Ayu-light-owl', 'url': 'https://raw.githubusercontent.com/js-oh/ayu-light-owl/master/images/ayu-light-owl-script-screenshot.png'},
    {'theme_name': 'ayu dark', 'url': 'https://raw.githubusercontent.com/davidgibsonp/ayu-rstudio/master/assets/dark.png'},
    {'theme_name': 'Ayu Light', 'url': 'https://raw.githubusercontent.com/davidgibsonp/ayu-rstudio/master/assets/light.png'},
    {'theme_name': 'ayu mirage', 'url': 'https://raw.githubusercontent.com/davidgibsonp/ayu-rstudio/master/assets/mirage.png'},
    {'theme_name': 'Barbie Dark', 'url': 'https://user-images.githubusercontent.com/83481390/208359464-8482471f-f364-40c2-b793-1685b470fef9.png'},
    {'theme_name': 'Barbie Light', 'url': 'https://user-images.githubusercontent.com/83481390/208359433-27dfa486-e00a-452e-afb5-c5a05cf54807.png'},
    {'theme_name': 'base16 3024 {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_3024.png'},
    {'theme_name': 'base16 Apathy {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_apathy.png'},
    {'theme_name': 'base16 Ashes {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_ashes.png'},
    {'theme_name': 'base16 Atelier Cave {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_cave.png'},
    {'theme_name': 'base16 Atelier Cave Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_cave_light.png'},
    {'theme_name': 'base16 Atelier Dune {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_dune.png'},
    {'theme_name': 'base16 Atelier Dune Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_dune_light.png'},
    {'theme_name': 'base16 Atelier Estuary {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_estuary.png'},
    {'theme_name': 'base16 Atelier Estuary Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_estuary_light.png'},
    {'theme_name': 'base16 Atelier Forest {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_forest.png'},
    {'theme_name': 'base16 Atelier Forest Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_forest_light.png'},
    {'theme_name': 'base16 Atelier Heath {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_heath.png'},
    {'theme_name': 'base16 Atelier Heath Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_heath_light.png'},
    {'theme_name': 'base16 Atelier Lakeside {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_lakeside.png'},
    {'theme_name': 'base16 Atelier Lakeside Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_lakeside_light.png'},
    {'theme_name': 'base16 Atelier Plateau {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_plateau.png'},
    {'theme_name': 'base16 Atelier Plateau Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_plateau_light.png'},
    {'theme_name': 'base16 Atelier Savanna {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_savanna.png'},
    {'theme_name': 'base16 Atelier Savanna Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_savanna_light.png'},
    {'theme_name': 'base16 Atelier Seaside {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_seaside.png'},
    {'theme_name': 'base16 Atelier Seaside Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_seaside_light.png'},
    {'theme_name': 'base16 Atelier Sulphurpool {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_sulphurpool.png'},
    {'theme_name': 'base16 Atelier Sulphurpool Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_atelier_sulphurpool_light.png'},
    {'theme_name': 'base16 Bespin {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_bespin.png'},
    {'theme_name': 'base16 Brewer {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_brewer.png'},
    {'theme_name': 'base16 Bright {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_bright.png'},
    {'theme_name': 'base16 Chalk {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_chalk.png'},
    {'theme_name': 'base16 Codeschool {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_codeschool.png'},
    {'theme_name': 'base16 Cupcake {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_cupcake.png'},
    {'theme_name': 'base16 Darktooth {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_darktooth.png'},
    {'theme_name': 'base16 Default Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_default_dark.png'},
    {'theme_name': 'base16 Default Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_default_light.png'},
    {'theme_name': 'base16 Dracula {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_dracula.png'},
    {'theme_name': 'base16 Eighties {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_eighties.png'},
    {'theme_name': 'base16 Embers {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_embers.png'},
    {'theme_name': 'base16 Flat {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_flat.png'},
    {'theme_name': 'base16 Google Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_google_dark.png'},
    {'theme_name': 'base16 Google Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_google_light.png'},
    {'theme_name': 'base16 Grayscale Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_grayscale_dark.png'},
    {'theme_name': 'base16 Grayscale Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_grayscale_light.png'},
    {'theme_name': 'base16 Green Screen {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_green_scren.png'},
    {'theme_name': 'base16 Gruvbox dark, hard {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_dark__hard.png'},
    {'theme_name': 'base16 Gruvbox dark, medium {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_dark__medium.png'},
    {'theme_name': 'base16 Gruvbox dark, pale {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_dark__pale.png'},
    {'theme_name': 'base16 Gruvbox dark, soft {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_dark__soft.png'},
    {'theme_name': 'base16 Gruvbox light, hard {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_light__hard.png'},
    {'theme_name': 'base16 Gruvbox light, medium {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_light__medium.png'},
    {'theme_name': 'base16 Gruvbox light, soft {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_gruvbox_light__soft.png'},
    {'theme_name': 'base16 Harmonic16 Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_harmonic16_dark.png'},
    {'theme_name': 'base16 Harmonic16 Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_harmonic16_light.png'},
    {'theme_name': 'base16 Hopscotch {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_hopscotch.png'},
    {'theme_name': 'base16 IR Black {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_ir_black.png'},
    {'theme_name': 'base16 IR Isotope {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_ir_isotope.png'},
    {'theme_name': 'base16 London Tube {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_london_tube.png'},
    {'theme_name': 'base16 Macintosh {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_macintosh.png'},
    {'theme_name': 'base16 Marrakesh {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_marrakesh.png'},
    {'theme_name': 'base16 Materia {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_materia.png'},
    {'theme_name': 'base16 Mexico Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_mexico_light.png'},
    {'theme_name': 'base16 Mocha {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_mocha.png'},
    {'theme_name': 'base16 Monokai {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_monokai.png'},
    {'theme_name': 'base16 Nord {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_nord.png'},
    {'theme_name': 'base16 Ocean {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_ocean.png'},
    {'theme_name': 'base16 OceanicNext {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_oceanicnext.png'},
    {'theme_name': 'base16 OneDark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_onedark.png'},
    {'theme_name': 'base16 Paraiso {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_paraiso.png'},
    {'theme_name': 'base16 PhD {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_phd.png'},
    {'theme_name': 'base16 Pico {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_pico.png'},
    {'theme_name': 'base16 Pop {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_pop.png'},
    {'theme_name': 'base16 Railscasts {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_railscasts.png'},
    {'theme_name': 'base16 Rebecca {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_rebecca.png'},
    {'theme_name': 'base16 Seti UI {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_seti_ui.png'},
    {'theme_name': 'base16 Shapeshifter {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_shapeshifter.png'},
    {'theme_name': 'base16 Solar Flare {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_solar_flare.png'},
    {'theme_name': 'base16 Solarized Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_solarized_dark.png'},
    {'theme_name': 'base16 Solarized Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_solarized_light.png'},
    {'theme_name': 'base16 Spacemacs {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_spacemacs.png'},
    {'theme_name': 'base16 Summerfruit Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_summerfruit_dark.png'},
    {'theme_name': 'base16 Summerfruit Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_summerfruit_false.png'},
    {'theme_name': 'base16 Tomorrow {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_tomorrow.png'},
    {'theme_name': 'base16 Tomorrow Night {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_tomorrow_night.png'},
    {'theme_name': 'base16 Twilight {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_twilight.png'},
    {'theme_name': 'base16 Unikitty Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_unikitty_light.png'},
    {'theme_name': 'base16 Woodland {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/base16_woodland.png'},
    {'theme_name': 'Black', 'url': 'https://user-images.githubusercontent.com/37285516/205855171-1a4ec82b-4a27-4b3b-b35b-bcb6e060a996.jpg'},
    {'theme_name': 'Breeze Dark', 'url': 'https://raw.githubusercontent.com/estasys/rstheme/blob/main/img/breeze-dark.png'},
    {'theme_name': 'BreezeDark', 'url': 'https://raw.githubusercontent.com/nnamliehbes/Breeze-RStudio-Theme/master/Breeze_Dark.png'},
    {'theme_name': 'BreezeDefault', 'url': 'https://github.com/nnamliehbes/Breeze-RStudio-Theme/master/BreezeDefault.png'},
    {'theme_name': 'Catppuccin', 'url': 'https://user-images.githubusercontent.com/65104127/157345412-229efdc5-dde7-441b-98f3-0e43208a7fba.png'},
    {'theme_name': 'catppuccin-frappe', 'url': 'https://raw.githubusercontent.com/catppuccin/rstudio/main/assets/frappe.webp'},
    {'theme_name': 'catppuccin-latte', 'url': 'https://raw.githubusercontent.com/catppuccin/rstudio/main/assets/latte.webp'},
    {'theme_name': 'catppuccin-macchiato', 'url': 'https://raw.githubusercontent.com/catppuccin/rstudio/main/assets/macchiato.webp'},
    {'theme_name': 'catppuccin-mocha', 'url': 'https://raw.githubusercontent.com/catppuccin/rstudio/main/assets/mocha.webp'},
    {'theme_name': 'darculaR', 'url': 'https://user-images.githubusercontent.com/22990100/178132089-3ab80acc-b47c-4de5-a163-80052ef34bb3.png'},
    {'theme_name': 'DarkThemeRStudio', 'url': 'https://user-images.githubusercontent.com/77588215/147927633-3443c830-13d2-4497-959a-f1638ec08c0c.png'},
    {'theme_name': 'Dracula', 'url': 'https://raw.githubusercontent.com/dracula/rstudio/master/screenshot.png'},
    {'theme_name': 'Driven Snow', 'url': 'https://raw.githubusercontent.com/mkearney/driven-snow/master/img/screen-shot.png'},
    {'theme_name': 'Elm dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/elm_dark.png'},
    {'theme_name': 'Elm light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/elm_light.png'},
    {'theme_name': 'Embark', 'url': 'https://raw.githubusercontent.com/eric-hunt/embark.rstheme/blob/main/images/screenshot_notebook_console.png'},
    {'theme_name': 'Epergoes (Light)', 'url': 'https://github.com/DesiQuintans/epergoes/raw/main/readme_files/preview_r.png'},
    {'theme_name': 'EvangelionUnit01', 'url': 'screenshot'},
    {'theme_name': 'Fairyfloss {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/fairyfloss.png'},
    {'theme_name': 'Fairyfloss Dark', 'url': 'https://raw.githubusercontent.com/Z3tt/fairlyfloss-dark/master/img/fairlyfloss-dark.png'},
    {'theme_name': 'Fastverse Dark', 'url': 'https://raw.githubusercontent.com/fastverse/codethemes/main/previews/fastverse_dark.png'},
    {'theme_name': 'Fastverse Light', 'url': 'https://raw.githubusercontent.com/fastverse/codethemes/main/previews/fastverse_light.png'},
    {'theme_name': 'Fringe', 'url': 'https://raw.githubusercontent.com/eviolette/RStudioThemes/master/Fringe/Fringe.png'},
    {'theme_name': 'Galaxy', 'url': 'https://raw.githubusercontent.com/cobriant/vaporwave.rstheme/main/galaxy.png'},
    {'theme_name': 'gamelad', 'url': 'https://raw.githubusercontent.com/matt-dray/gamelad/main/img/rstudio-safar6-gamelad-vt323.png'},
    {'theme_name': 'Grubber', 'url': 'https://raw.githubusercontent.com/RobertMyles/grubber/master/grubber.png'},
    {'theme_name': 'gruvboxr', 'url': 'https://raw.githubusercontent.com/tallguyjenks/gruvboxr/master/inst/media/preview.png'},
    {'theme_name': 'Hacker Green', 'url': 'https://raw.githubusercontent.com/jsta/hacker_green/master/screenshot.png'},
    {'theme_name': 'Horizon Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/horizon_dark.png'},
    {'theme_name': 'Horizon Synthwave {custom-rsthemes}', 'url': 'https://raw.githubusercontent.com/seanlaidlaw/HorizonSynth-Rstudio-Theme/master/img/rstudio_themed.png'},
    {'theme_name': 'Kandle', 'url': 'https://raw.githubusercontent.com/TheMrKingent/KandleTheme/main/img/code_ed.png'},
    {'theme_name': 'KandleDarkerPlot', 'url': 'https://raw.githubusercontent.com/TheMrKingent/KandleTheme/main/img/plotscreencap.gif'},
    {'theme_name': 'Kiss', 'url': 'https://raw.githubusercontent.com/rileytwo/kiss/main/inst/RStudio-1.png'},
    {'theme_name': 'Kosmosepralle', 'url': 'https://raw.githubusercontent.com/mvainre/Kosmosepralle/main/Illustration.PNG'},
    {'theme_name': 'Macaron', 'url': 'https://user-images.githubusercontent.com/127744117/225313248-f1695d8a-ee0c-449c-92bc-ba9cbdda7e58.png'},
    {'theme_name': 'masterX RStudio', 'url': 'https://raw.githubusercontent.com/irwingss/masterX-RStudio-Theme/main/masterXtema.png'},
    {'theme_name': 'Material', 'url': 'https://raw.githubusercontent.com/lusignan/RStudio-Material-Theme/main/img/material-preview.png'},
    {'theme_name': 'Material {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/material.png'},
    {'theme_name': 'Material Darker', 'url': 'https://raw.githubusercontent.com/lusignan/RStudio-Material-Theme/main/img/material-darker-preview.png'},
    {'theme_name': 'Material Darker {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/material_darker.png'},
    {'theme_name': 'Material Lighter', 'url': 'https://raw.githubusercontent.com/lusignan/RStudio-Material-Theme/main/img/material-lighter-preview.png'},
    {'theme_name': 'Material Lighter {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/material_lighter.png'},
    {'theme_name': 'Material Ocean', 'url': 'https://raw.githubusercontent.com/lusignan/RStudio-Material-Theme/main/img/material-ocean-preview.png'},
    {'theme_name': 'Material Ocean {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/material_ocean.png'},
    {'theme_name': 'Material Palenight', 'url': 'https://raw.githubusercontent.com/lusignan/RStudio-Material-Theme/main/img/material-palenight-preview.png'},
    {'theme_name': 'Material Palenight {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/material_palenight.png'},
    {'theme_name': 'matrix_glow', 'url': 'https://raw.githubusercontent.com/AlessioMR/matrix_glow/master/matrix_glow_Rscript_pic.PNG'},
    {'theme_name': 'mayukai-mirage-darker', 'url': 'https://raw.githubusercontent.com/graiffgarcia/ayu-ish-rstudio/master/assets/mayukai-mirage-darker.png'},
    {'theme_name': 'MineR', 'url': 'https://raw.githubusercontent.com/jrh-dev/RStudio-Themes/main/img/miner.png'},
    {'theme_name': 'Mojave Dark', 'url': 'https://raw.githubusercontent.com/patrickshox/Mojave-Dark-RStudio-Theme/master/Demo%20Images%20and%20Gifs/Main.png'},
    {'theme_name': 'Monokai Dimmed', 'url': 'https://raw.githubusercontent.com/thedbcooper/rstudio-theme-monokai-dimmed/main/screenshots/img2.png'},
    {'theme_name': 'My Theme', 'url': 'https://raw.githubusercontent.com/brunaw/my-theme/master/img/example.png'},
    {'theme_name': 'Nebelreich', 'url': 'https://private-user-images.githubusercontent.com/147148525/292896857-ebee5648-87dc-4870-b0b0-e100c6fd38cc.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTc3NTMsIm5iZiI6MTcxMzgxNzQ1MywicGF0aCI6Ii8xNDcxNDg1MjUvMjkyODk2ODU3LWViZWU1NjQ4LTg3ZGMtNDg3MC1iMGIwLWUxMDBjNmZkMzhjYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQyMDI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jODhkZWQ5MzJiNTIxYmMxYWU4ZmM0NDM0N2JiYjViYTE4NTFiMjUxMWFkMTVhYjZjY2Q1OGM2NDU0NWJjMDY2JlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.R0lQVrXISW2Ka1uoxWZceTDItVLWVmbR6rawKbix1w4'},
    {'theme_name': 'Necklace Contrast', 'url': 'https://raw.githubusercontent.com/basiliomp/r-custom/master/illustrative-screenshot.png'},
    {'theme_name': 'NHL Light', 'url': 'https://raw.githubusercontent.com/themechanicalbear/nhlthemes/master/nhlthemes_demo.gif'},
    {'theme_name': 'Night Owl', 'url': 'https://raw.githubusercontent.com/batpigandme/night-owlish/master/img/night-owlish-rstudio-full.png'},
    {'theme_name': 'Night Owl {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/night_owl.png'},
    {'theme_name': 'Nord-RStudio', 'url': 'https://raw.githubusercontent.com/max-alletsee/nord-rstudio/master/img/nord-rstudio-full.png'},
    {'theme_name': 'Nord (edavidaja)', 'url': 'https://raw.githubusercontent.com/edavidaja/nord-rstudio/master/shiny.png'},
    {'theme_name': 'Nord (lusignan)', 'url': 'https://raw.githubusercontent.com/lusignan/Nord-RStudio/master/nord-rstudio-preview.png'},
    {'theme_name': 'Nord Polar Night', 'url': 'https://raw.githubusercontent.com/siegerts/rstudio-nord-theme/master/rstudio-nord.png'},
    {'theme_name': 'Nord Polar Night Aurora {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/nord_polar_night_aurora.png'},
    {'theme_name': 'Oceanic - Eighties', 'url': 'https://raw.githubusercontent.com/gadenbuie/oceanic-eighties/master/oceanic-eighties.png'},
    {'theme_name': 'Oceanic Plus {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/oceanic_plus.png'},
    {'theme_name': 'One Dark {Inspired}', 'url': 'https://raw.githubusercontent.com/dyavorsky/atom-inspired-rstudio-theme/main/atom-inspired.png'},
    {'theme_name': 'One Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/one_dark.png'},
    {'theme_name': 'One Dark Pro', 'url': 'https://raw.githubusercontent.com/johnnybarrels/rstudio-one-dark-pro-theme/master/img/rstudio-onedark.png'},
    {'theme_name': 'One Dark Pro {jrh-dev}', 'url': 'https://raw.githubusercontent.com/jrh-dev/RStudio-Themes/main/img/onedark.png'},
    {'theme_name': 'One Monokai', 'url': 'https://raw.githubusercontent.com/jcasasn/rstudio-theme-one-monokai/main/screenshots/img1.png'},
    {'theme_name': 'Orchideen', 'url': 'https://private-user-images.githubusercontent.com/147148525/292895179-566a42cd-1e29-470e-937c-64582cd87ae6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTc3NTMsIm5iZiI6MTcxMzgxNzQ1MywicGF0aCI6Ii8xNDcxNDg1MjUvMjkyODk1MTc5LTU2NmE0MmNkLTFlMjktNDcwZS05MzdjLTY0NTgyY2Q4N2FlNi5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQyMDI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1hNzQ3MDIxNDY0MzkxYTNlMDIzNTZkMDAwNGFlYjFlNTM0ODhlZDYyMTc0MjBiMGVhZWUyODcwZjA1NGM3MDdjJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.jvblDo9PWASHDmeuVeI2ot5FlSQIWVe9QMHQxOfV3fE'},
    {'theme_name': 'Outrun (Arcade)', 'url': 'https://raw.githubusercontent.com/camkay/outRun/master/example/outrun_theme_example.png'},
    {'theme_name': 'Outrun (Electric)', 'url': 'https://raw.githubusercontent.com/JeffreyZammit/Rstudio-outrun-theme/main/example/example.PNG'},
    {'theme_name': 'Pagomba', 'url': 'https://raw.githubusercontent.com/pgomba/Rstudio_theme/main/Capture.PNG'},
    {'theme_name': 'Pebble-dark', 'url': 'https://raw.githubusercontent.com/DesiQuintans/pebble-themes/master/images/pebble-dark.png'},
    {'theme_name': 'Pebble-grey', 'url': 'https://raw.githubusercontent.com/DesiQuintans/pebble-themes/master/images/pebble-grey.png'},
    {'theme_name': 'Pebble-safe', 'url': 'https://raw.githubusercontent.com/DesiQuintans/pebble-themes/master/images/pebble-safe.png'},
    {'theme_name': 'Pebble-Safe Dark', 'url': 'https://raw.githubusercontent.com/DesiQuintans/Pebble-safe/master/_img/dark.png'},
    {'theme_name': 'Pebble-Safe Light', 'url': 'https://raw.githubusercontent.com/DesiQuintans/Pebble-safe/master/_img/light.png'},
    {'theme_name': 'Poolside {rsthemes}', 'url': 'https://raw.githubusercontent.com/nsgrantham/poolside-rstudio/main/poolside-screenshot.png'},
    {'theme_name': 'Prelude', 'url': 'https://raw.githubusercontent.com/lyriodendron/Prelude-Rstudio-theme/main/prelude_screenshot.png'},
    {'theme_name': 'Qwick_Ambiance', 'url': 'https://raw.githubusercontent.com/qwickmalik/qwick_ambiance/main/img/qwick_ambiance.png'},
    {'theme_name': 'RedStudio', 'url': 'https://raw.githubusercontent.com/jdonland/rstheme/blob/main/screenshot.PNG'},
    {'theme_name': 'rscodeio (anthonynorth)', 'url': 'https://raw.githubusercontent.com/anthonynorth/rscodeio/master/inst/media/rscodeio.png'},
    {'theme_name': 'Sahyadri', 'url': 'https://raw.githubusercontent.com/kvenkita/sahyadri/master/example.png'},
    {'theme_name': 'Serendipity Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/serendipity_dark.png'},
    {'theme_name': 'Serendipity Light {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/serendipity_light.png'},
    {'theme_name': 'Simple Nord (Sophychen)', 'url': 'https://raw.githubusercontent.com/sophychen79/themes/main/simple-nord.png'},
    {'theme_name': 'Solarized Dark {rsthemes}', 'url': 'https://raw.githubusercontent.com/gadenbuie/rsthemes/assets/themes/solarized_dark.png'},
    {'theme_name': 'Synthwave85', 'url': 'https://raw.githubusercontent.com/jnolis/synthwave85/master/example.png'},
    {'theme_name': 'SynthwaveBlack', 'url': 'https://raw.githubusercontent.com/roshandarji/synthwaveBLACK/master/synthwaveBLACK_example.png'},
    {'theme_name': 'Tanjiro', 'url': 'https://raw.githubusercontent.com/mrmorgan17/Tanjiro/main/Tanjiro%20Screen%20Shot.png'},
    {'theme_name': 'Umi', 'url': 'https://raw.githubusercontent.com/braudm/rstudio_umi_theme/master/umi-theme_example.PNG'},
    {'theme_name': 'V-Ink Flavoured', 'url': 'https://raw.githubusercontent.com/bgonzalezbustamante/v-ink-flavoured/main/images/vink.png'},
    {'theme_name': 'vaporwave', 'url': 'https://raw.githubusercontent.com/cobriant/vaporwave.rstheme/main/Screen%20Shot.png'},
    {'theme_name': 'Viridis', 'url': 'https://raw.githubusercontent.com/Z3tt/viridis-theme/master/img/viridis-theme-preview.png'},
    {'theme_name': 'VScodeTheme', 'url': 'https://user-images.githubusercontent.com/63495216/110667938-0f4d4b00-81cb-11eb-943e-f5951dbed137.png'},
    {'theme_name': 'VSR', 'url': 'https://github.com/scott-brown-1/VSR/raw/main/images/VSR-example.jpg'},
    {'theme_name': 'Wilde Freie See', 'url': 'https://private-user-images.githubusercontent.com/147148525/292894886-c81739eb-34ca-4e70-afcf-a5a87e37fc56.mp4?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM4MTc3NTMsIm5iZiI6MTcxMzgxNzQ1MywicGF0aCI6Ii8xNDcxNDg1MjUvMjkyODk0ODg2LWM4MTczOWViLTM0Y2EtNGU3MC1hZmNmLWE1YTg3ZTM3ZmM1Ni5tcDQ_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwNDIyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDQyMlQyMDI0MTNaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT1jYjA5N2M5ZjlkYzllMGNlMjM2OGYwMzE0YWE1N2Y4YTk3NWNmYzhiNTc4ZmEyMDQzZTIwZmRmYTZiOTIyYTNiJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.POhwUek1pFSozt1Z9s5xUcrT8a70rtx5I_fURDCy2nY'},
    {'theme_name': 'Yule RStudio', 'url': 'https://raw.githubusercontent.com/gadenbuie/yule-rstudio/master/images/floating-rstudio.png'},
    {'theme_name': 'Zinogre', 'url': 'https://raw.githubusercontent.com/takemal-studio/RStudio_Zinogre_theme/master/img/sample_code.png'},

]

# Function to download each image
for theme in themes:
    url = theme['url']
    if url.startswith('http'):  # Only proceed if the URL is valid
        try:
            response = requests.get(url)
            if response.status_code == 200:
                file_path = os.path.join(output_dir, theme['theme_name'].replace(' ', '_') + '.png')
                with open(file_path, 'wb') as f:
                    f.write(response.content)
                print(f"Downloaded: {theme['theme_name']}")
            else:
                print(f"Failed to download: {theme['theme_name']}, Status Code: {response.status_code}")
        except Exception as e:
            print(f"Error downloading {theme['theme_name']}: {e}")
    else:
        print(f"Invalid URL for {theme['theme_name']}: {url}")
